name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for posting your first issue, we will be happy to help you with it !!"
        pr-message: "Thank you for pulling our repo, we are happy that you are able to contribute in the repo. Happy Coding :) "
